### ISSUE TITLE
Cannot find module '../../utils/walk-dir'

### ISSUE THREAD

**Issue by geocine** [ashinzekene/generator-nestjs-app#1]
### OS and Version?
> macOS High Sierra

### Versions
> v0.1.1

### Repro steps
```
yo nestjs-app
```
### The log given by the failure.
```
Error: Cannot find module '../../utils/walk-dir'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/geocine/.nvm/versions/node/v8.0.0/lib/node_modules/generator-nestjs-app/generators/app/index.js:6:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

### Mention any other details that might be useful.
 By the way , **README.md** is outdated it should be `yo nestjs-app` not `yo nestjs` as that points to a different generator

**Comment by ashinzekene** [comment]
Thanks for pointing that out
